insert into public.media_mentions (
  source_url, canonical_url, dedupe_key, source_name, platform, author_name, author_role,
  title, quote, summary, mention_type, related_entities, occurred_at, status,
  published_at, collector, raw_payload
)
values
  ('https://www.gob.pe/institucion/proinnovate/noticias/1360546-innova-como-ellas-historias-de-mujeres-que-transforman-el-sector-empresarial-y-productivo-del-pais', 'https://www.gob.pe/institucion/proinnovate/noticias/1360546-innova-como-ellas-historias-de-mujeres-que-transforman-el-sector-empresarial-y-productivo-del-pais', 'initial-proinnovate-apirobotics', 'ProInnóvate', 'web', 'ProInnóvate', null, 'ApiRobotics destacada por ProInnóvate', null, 'ProInnóvate destacó las colmenas inteligentes de ApiRobotics y su monitoreo en tiempo real para fortalecer la polinización agrícola.', 'news', array['ApiRobotics'], '2026-03-05T00:00:00Z', 'published', '2026-08-19T00:00:00Z', 'initial-curation', '{"source_kind":"independent"}'::jsonb),
  ('https://ucontinental.edu.pe/noticias/egresados-de-la-universidad-continental-ganan-premio-avonni-2026/', 'https://ucontinental.edu.pe/noticias/egresados-de-la-universidad-continental-ganan-premio-avonni-2026/', 'initial-avonni-apirobotics', 'Universidad Continental', 'web', 'Universidad Continental', null, 'ApiRobotics gana Premio Avonni-CCL', null, 'ApiRobotics obtuvo el reconocimiento Avonni-CCL en Recursos Naturales y Acción Climática por su propuesta de colmenas robotizadas con monitoreo en tiempo real.', 'award', array['ApiRobotics'], '2026-03-20T00:00:00Z', 'published', '2026-08-19T00:00:00Z', 'initial-curation', '{"source_kind":"independent"}'::jsonb),
  ('https://pe.linkedin.com/company/incubadorascale', 'https://pe.linkedin.com/company/incubadorascale', 'initial-scale-big12', 'Incubadora Scale / Social Innovation Hub', 'linkedin', 'Incubadora Scale', null, 'ApiRobotics seleccionada para BIG 12', null, 'Scale felicitó a María Arana y Hans Camayo por la selección de ApiRobotics en la generación BIG 12 de Start-Up Chile y destacó su proyección internacional.', 'testimonial', array['ApiRobotics'], null, 'published', '2026-08-19T00:00:00Z', 'initial-curation', '{"source_kind":"ally"}'::jsonb),
  ('https://es.linkedin.com/posts/biohubventure_igbm-presente-llevando-la-biotecnolog%C3%ADa-activity-7445839319958704128-aQ41', 'https://es.linkedin.com/posts/biohubventure_igbm-presente-llevando-la-biotecnolog%C3%ADa-activity-7445839319958704128-aQ41', 'initial-igbm-unalm', 'Instituto de Genética Barbara McClintock (IGBM)', 'linkedin', 'IGBM', null, 'BioHubVenture presentada en la UNALM', null, 'IGBM presentó a BioHubVenture como una iniciativa orientada a potenciar startups biotecnológicas.', 'mention', array['BioHubVenture'], null, 'published', '2026-08-19T00:00:00Z', 'initial-curation', '{"source_kind":"ally"}'::jsonb),
  ('https://pe.linkedin.com/company/biogenia', 'https://pe.linkedin.com/company/biogenia', 'initial-biogenia-deeptech', 'Biogenia', 'linkedin', 'Biogenia', null, 'BioHubVenture como plataforma de venture building', null, 'Biogenia incluyó a BioHubVenture entre los vehículos que buscan escalar startups deep-tech surgidas de universidades y centros de investigación.', 'mention', array['BioHubVenture'], null, 'published', '2026-08-19T00:00:00Z', 'initial-curation', '{"source_kind":"ally"}'::jsonb),
  ('https://pe.linkedin.com/company/biohubventure', 'https://pe.linkedin.com/company/biohubventure', 'initial-mitchell-mentor', 'BioHubVenture / LinkedIn', 'linkedin', 'Mitchell Jesús Lázaro Díaz', 'Mentor del Bootcamp Internacional BHV 2026', 'Testimonio de mentor', 'Gracias a BioHubVenture y a todos sus aliados por convertir nuestro propósito en acción real.', null, 'testimonial', array['BioHubVenture'], null, 'published', '2026-08-19T00:00:00Z', 'initial-curation', '{"source_kind":"participant"}'::jsonb),
  ('https://www.linkedin.com/company/biohubventure', 'https://www.linkedin.com/company/biohubventure', 'initial-andres-participant', 'BioHubVenture / LinkedIn', 'linkedin', 'Andrés Calderón', 'Participante del Bootcamp Internacional Bioemprendedores 2026', 'Testimonio de participante', 'Gracias a BioHubVenture y sus aliados por confiar en el proyecto y apostar por el talento científico de la región.', null, 'testimonial', array['BioHubVenture'], null, 'published', '2026-08-19T00:00:00Z', 'initial-curation', '{"source_kind":"participant"}'::jsonb),
  ('https://es.linkedin.com/posts/anii_deinter%C3%A9sanii-activity-7455344363393589248-31VQ', 'https://es.linkedin.com/posts/anii_deinter%C3%A9sanii-activity-7455344363393589248-31VQ', 'initial-program-results', 'BioHubVenture', 'linkedin', 'BioHubVenture', null, 'Resultados del Bootcamp Internacional Bioemprendedores 2026', null, 'BioHubVenture reportó 12 startups egresadas: ApiRobotics fue primera, Pompom segunda, MIZETA tercera y CRYBS sexta. Es una publicación institucional propia.', 'mention', array['BioHubVenture','ApiRobotics','Pompom','MIZETA','CRYBS'], null, 'published', '2026-08-19T00:00:00Z', 'initial-curation', '{"source_kind":"self_reported"}'::jsonb),
  ('https://pe.linkedin.com/in/hanscamayo', 'https://pe.linkedin.com/in/hanscamayo', 'initial-hans-founder', 'Hans Camayo / LinkedIn', 'linkedin', 'Hans Camayo Basurto', 'Co-founder de ApiRobotics', 'Comentario de founder sobre la segunda cohorte', null, 'Hans Camayo destacó el trabajo de la segunda cohorte y mencionó a ApiRobotics, Pompón, MIZETA, Dragosense y CRYBS.', 'testimonial', array['BioHubVenture','ApiRobotics','Pompom','MIZETA','CRYBS'], null, 'published', '2026-08-19T00:00:00Z', 'initial-curation', '{"source_kind":"founder"}'::jsonb),
  ('https://www.linkedin.com/company/biohubventure/', 'https://www.linkedin.com/company/biohubventure/', 'initial-crybs-demo-day', 'CRYBS / LinkedIn', 'linkedin', 'CRYBS', null, 'CRYBS reconocida como startup más invertible', null, 'CRYBS comunicó que fue reconocida como la startup más invertible durante el Demo Day. La mención se atribuye a la propia startup.', 'award', array['CRYBS','BioHubVenture'], null, 'published', '2026-08-19T00:00:00Z', 'initial-curation', '{"source_kind":"self_reported"}'::jsonb)
on conflict (dedupe_key) do nothing;
